// Generated by ReScript, PLEASE EDIT WITH CARE


function main(param) {
  console.log("P3");
  console.log(String(256) + " " + String(256));
  console.log("255");
}

export {
  main ,
}
/* No side effect */
