// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vec3 = require("./Vec3.bs.js");

function rayAt(ray, t) {
  return Vec3.addVec3(ray.origin, Vec3.multiplyFloat(ray.direction, t));
}

exports.rayAt = rayAt;
/* No side effect */
